version: '3.8'

services:
  compal_rag:
    image: compal_rag:py310 # compal_rag:latest
    ports:
      - "7861:7861"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - protocal=http
      - url=text-generation-webui
      - port=5001
      - SERVER_URL=text-generation-webui
      - OPENAI_API_KEY=sk-111111111111111111111111111111111111111111111111
      - OPENAI_API_BASE=http://text-generation-webui:5001/v1
      - OPENAI_BASE_URL=http://text-generation-webui:5001/v1
    networks:
      - compal_rag-net
    
  qdrant:
    container_name: qdrant
    hostname: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant_data
    networks:
      - compal_rag-net

networks:
  compal_rag-net:
    external: true